---
- include: dotfiles.yml
  sudo_user: "{{ dotfiles_user }}"
  when: user_settings[dotfiles_user].dotfiles_repo and user_settings[dotfiles_user].dotfiles_links and dotfiles_run_{{ dotfiles_user }} is not defined
  tags:
    - dotfiles

- set_fact: dotfiles_run_{{ dotfiles_user }}=true
  when: dotfiles_run_{{ dotfiles_user }} is not defined
