---
- fail: msg="This role handles a max of 10 users."
  when: "10 < user_setup_users|length"

- name: Install tools
  apt: pkg={{ item }}
       state=installed
  with_items:
    - silversearcher-ag
    - htop
