---
- name: Make gotools directory
  file: path=/home/{{ dotfiles_user }}/src/gotools
        state=directory

- name: Install gocode
  command: go get -u github.com/nsf/gocode
  environment:
    GOPATH: /home/{{ dotfiles_user }}/src/gotools
    GOBIN: /home/{{ dotfiles_user }}/bin
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}

- name: Install goimports
  command: go get -u code.google.com/p/go.tools/cmd/goimports
  environment:
    GOPATH: /home/{{ dotfiles_user }}/src/gotools
    GOBIN: /home/{{ dotfiles_user }}/bin
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}

- name: Install gotags
  command: go get -u github.com/jstemmer/gotags
  environment:
    GOPATH: /home/{{ dotfiles_user }}/src/gotools
    GOBIN: /home/{{ dotfiles_user }}/bin
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
