---
- name: Install vim and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - vim-athena
    - ack-grep
    - exuberant-ctags
    - mercurial

- include: golang.yml
  sudo_user: "{{ dotfiles_user }}"
  when: use_golang
  tags:
    - vim_golang

- include: vundle.yml
  sudo_user: "{{ dotfiles_user }}"
  when: use_vundle
  tags:
    - vundle

- name: Check vim version
  command: vim --version
  register: vim_version_info
  changed_when: false


- name: Check for YouCompleteMe
  command: /usr/bin/stat /home/{{ dotfiles_user }}/.vim/bundle/YouCompleteMe
  register: check_you_complete_me
  changed_when: false
  failed_when: false

- name: Install YouCompleteMe dependencies
  apt: pkg={{ item }} state=installed
  when: check_you_complete_me.rc == 0 and '7.4' in vim_version_info.stdout
  with_items:
    - cmake
    - build-essential
    - python-dev

- include: you_complete_me.yml
  sudo_user: "{{ dotfiles_user }}"
  when: check_you_complete_me is defined and check_you_complete_me.rc == 0 and '7.4' in vim_version_info.stdout


- name: Check for ctrlp cmatcher
  command: /usr/bin/stat /home/{{ dotfiles_user }}/.vim/bundle/ctrlp-cmatcher
  register: check_ctrlp_cmatcher
  changed_when: false
  failed_when: false

- name: Install dependencies
  apt: pkg=python-dev state=installed
  when: check_ctrlp_cmatcher.rc == 0

- name: Compile ctrlp cmatcher
  command: ./install_linux.sh
           chdir=/home/{{ dotfiles_user }}/.vim/bundle/ctrlp-cmatcher
           creates=/home/{{ dotfiles_user }}/.vim/bundle/ctrlp-cmatcher/autoload/fuzzycomt.so
  when: check_ctrlp_cmatcher.rc == 0

- include: js.yml
  sudo_user: "{{ dotfiles_user }}"
  when: use_js
  tags:
    - vim_js
